services:
  wazuh.manager:
    build:
      context: server
      dockerfile: manager.Dockerfile
    hostname: wazuh.manager
    container_name: ResilMesh-Wazuh-Manager
    #restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - 1514:1514
      - 1515:1515
      - 514:514/udp
      - 55000:55000
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - agentless:/var/ossec/agentless
      - api_configuration:/var/ossec/api/configuration
      - logs:/var/ossec/logs
      - queue:/var/ossec/queue
      - var_multigroups:/var/ossec/var/multigroups
      - wodles:/var/ossec/wodles
      - ./server/config/wazuh_active_response:/var/ossec/active-response/bin
      - ./server/config/wazuh_etc:/var/ossec/etc
      - ./server/config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./server/config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./server/config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./server/config/wazuh_integrations:/var/ossec/integrations
      - ${PWD}/server/ossec.conf:/wazuh-config-mount/etc/ossec.conf
    networks:
      internal:
      resilmesh_network:
        ipv4_address: ${MANAGER_IP}

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.9.0
    hostname: wazuh.indexer
    container_name: ResilMesh-Wazuh-Indexer
    restart: always
    ports:
      - ${INDEXER_PORT}:9200
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - indexer-data:/var/lib/wazuh-indexer
      - ./server/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./server/config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ./server/config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ./server/config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./server/config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ./server/config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./server/config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
    networks:
      internal:

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.9.0
    hostname: wazuh.dashboard
    container_name: ResilMesh-Wazuh-Dashboard
    restart: always
    ports:
      - ${DASHBOARD_PORT}:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
      - ./server/config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./server/config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./server/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./server/config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./server/config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager
    networks:
      internal:

  wazuh.agent-ubuntu2204:
    build:
      context: agent
      dockerfile: ubuntu.Dockerfile
      args:
        manager_ip: ${MANAGER_IP}
    container_name: ResilMesh-Wazuh-Agent_Ubuntu_22.04
    ports:
      - ${OPENC2_ACTUATOR_PORT}:8080
    volumes:
      - agent-ossec:/var/ossec
      - ./agent/commands:/var/ossec/commands
      - ${PWD}/agent/ossec.conf:/var/ossec/etc/ossec.conf
    networks:
      resilmesh_network:
        ipv4_address: ${AGENT_IP_UBUNTU2204}

volumes:
  api_configuration:
  logs:
  queue:
  var_multigroups:
  integrations:
  active_response:
  agentless:
  wodles:
  filebeat_etc:
  filebeat_var:
  indexer-data:
  dashboard-config:
  dashboard-custom:
  agent-ossec:

networks:
  internal:
  resilmesh_network:
    external: true
