services:
  wazuh.agent-ubuntu:
    build:
      dockerfile: ubuntu.Dockerfile
      args:
        manager_ip: ${SERVER_IP}
    ports:
      - 8889:8080
    volumes:
      - wazuh-agent-ossec:/var/ossec
      - ./commands:/var/ossec/commands
      - ${PWD}/ossec.conf:/wazuh-config-mount/etc/ossec.conf
    networks:
      resilmesh_network:
        ipv4_address: ${AGENT_IP_UBUNTU2204}
volumes:
  wazuh-agent-ossec:
networks:
  resilmesh_network:
     external: true
